In [1]:
# import packages
import pandas as pd
from auxiliary.filter_functions import *
from auxiliary.search_algorithm import *
from results import *
from testing import *
from astroquery.vizier import Vizier
from astroquery.simbad import Simbad, SimbadClass
import os
import glob
from astropy.table import Table
import numpy as np
from astropy.io import fits
import time
import matplotlib.pyplot as plt
from astropy.stats import poisson_conf_interval
import scipy
import re

In [2]:
# plot multifig of filtered by variance candidates

parameters = [
    # {
    #     'date_range': [
    #         '2022-04-01',
    #         ''
    #     ],
    #     'window': 20,
    #     'exclusions': []
    # },
    # {
    #     'date_range': [
    #         '2015-01-01',
    #         '2022-04-01'
    #     ],
    #     'window': 20,
    #     'exclusions': []
    # },
    {
        'date_range': [
            '',
            '2015-01-01'
        ],
        'window': 20,
        'exclusions': []
    },
    # {
    #     'date_range': [
    #         '',
    #         ''
    #     ],
    #     'window': 50,
    #     'exclusions': [20]
    # }
]

for params in parameters:
    filename = f'output/candidates/candidates_w_{params["window"]}_ex_{"_".join([str(i) for i in params["exclusions"]])}_daterange_{params["date_range"][0]}_{params["date_range"][1]}.csv'

    candidates = pd.read_csv(filename, header=0, dtype=str)

    # plot multifig of filtered by variance candidates
    group_size = 7
    candidates = [candidates[i:i + group_size] for i in range(0, candidates.shape[0], group_size)]

    for i, group in enumerate(candidates):
        plot_light_curve_multifig(
            group, f'candidates_w_{params["window"]}_ex_{"_".join([str(i) for i in params["exclusions"]])}_daterange_{params["date_range"][0]}_{params["date_range"][1]}_{i}')

/home/jcrans/miniconda3/envs/ciao-4.16/lib/python3.11/site-packages/matplotlib/cbook.py:1699: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return math.isfinite(val)

No files found for 963
963 - Error: cannot unpack non-iterable int object

/home/jcrans/miniconda3/envs/ciao-4.16/lib/python3.11/site-packages/matplotlib/cbook.py:1699: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return math.isfinite(val)
/home/jcrans/miniconda3/envs/ciao-4.16/lib/python3.11/site-packages/matplotlib/cbook.py:1699: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return math.isfinite(val)
/home/jcrans/miniconda3/envs/ciao-4.16/lib/python3.11/site-packages/matplotlib/cbook.py:1699: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return math.isfinite(val)
/home/jcrans/miniconda3/envs/ciao-4.16/lib/python3.11/site-packages/matplotlib/cbook.py:1699: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return math.isfinite(val)
/home/jcrans/miniconda3/envs/ciao-4.16/lib/python3.11/site-packages/matplotlib/cbook.py:1699: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return math.isfinite(val)
/home/jcrans/miniconda3/envs/ciao-4.16/lib/python3.11/site-packages/matplotlib/cbook.py:1699: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return math.isfinite(val)
/home/jcrans/miniconda3/envs/ciao-4.16/lib/python3.11/site-packages/matplotlib/cbook.py:1699: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return math.isfinite(val)
/home/jcrans/miniconda3/envs/ciao-4.16/lib/python3.11/site-packages/matplotlib/cbook.py:1699: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return math.isfinite(val)
/home/jcrans/miniconda3/envs/ciao-4.16/lib/python3.11/site-packages/matplotlib/cbook.py:1699: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return math.isfinite(val)

No files found for 18
18 - Error: cannot unpack non-iterable int object
No files found for 18
18 - Error: cannot unpack non-iterable int object
No files found for 18
18 - Error: cannot unpack non-iterable int object
No files found for 18
18 - Error: cannot unpack non-iterable int object

/home/jcrans/miniconda3/envs/ciao-4.16/lib/python3.11/site-packages/matplotlib/cbook.py:1699: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return math.isfinite(val)
/home/jcrans/miniconda3/envs/ciao-4.16/lib/python3.11/site-packages/matplotlib/cbook.py:1699: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return math.isfinite(val)
/home/jcrans/miniconda3/envs/ciao-4.16/lib/python3.11/site-packages/matplotlib/cbook.py:1699: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return math.isfinite(val)
/home/jcrans/miniconda3/envs/ciao-4.16/lib/python3.11/site-packages/matplotlib/cbook.py:1699: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return math.isfinite(val)
/home/jcrans/miniconda3/envs/ciao-4.16/lib/python3.11/site-packages/matplotlib/cbook.py:1699: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return math.isfinite(val)

No files found for 581
581 - Error: cannot unpack non-iterable int object
No files found for 1431
1431 - Error: cannot unpack non-iterable int object

In [16]:
# plot multifig of filtered by variance candidates

parameters = [
    {
        'date_range': [
            '2022-04-01',
            ''
        ],
        'window': 20,
        'exclusions': []
    },
    {
        'date_range': [
            '2015-01-01',
            '2022-04-01'
        ],
        'window': 20,
        'exclusions': []
    },
    {
        'date_range': [
            '',
            '2015-01-01'
        ],
        'window': 20,
        'exclusions': []
    },
    {
        'date_range': [
            '',
            ''
        ],
        'window': 50,
        'exclusions': [20]
    }
]

index = 2

candidates = pd.read_csv(
    f'output/candidates/candidates_w_{parameters[index]["window"]}_ex_{"_".join([str(i) for i in parameters[index]["exclusions"]])}_daterange_{parameters[index]["date_range"][0]}_{parameters[index]["date_range"][1]}.csv', 
    header=0, 
    dtype=str
)

# get table
table = get_fxt_table_detections(candidates, 1)
table.drop(columns=['Previous Detection'], inplace=True)

# table
print(dataframe_to_latex(table))

\begin{table}[h]
    \centering
    \caption{}
    \begin{tabular}{ccccccccccc}
        \headerrow & \headercell{Id} & \headercell{ObsId} & \headercell{Exp. (ks)} & \headercell{Date} & \headercell{$T_{90}$ (ks)} & \headercell{RA (deg)} & \headercell{Dec (deg)} & \headercell{Off. Ang.} & \headercell{Pos. Unc.} & \headercell{S/N} \\
        \oddrow 1 & XRT 000519 & 803 & $28.5$ & 2000-05-19 & $15.8^{1.8}_{1.6}$ & $186.38158$ & $13.06645$ & $13.3^{\prime}$ & $0.46^{\prime\prime}$ & $107.9$ \\
        \evenrow 2 & XRTC 010809 & 1878 & $75.5$ & \makecell{2001-08-08/\\2001-08-09} & $56.2^{9.3}_{11.6}$ & $85.43966$ & $-1.90754$ & $0.8^{\prime}$ & $0.08^{\prime\prime}$ & $51.4$ \\
        \oddrow 3 & XRTC 010809 & 1878 & $75.5$ & \makecell{2001-08-08/\\2001-08-09} & $58.7^{8.4}_{31.4}$ & $85.45288$ & $-1.90446$ & $1.0^{\prime}$ & $0.29^{\prime\prime}$ & $12.4$ \\
        \evenrow 4 & XRTC 010809 & 1878 & $75.5$ & \makecell{2001-08-08/\\2001-08-09} & $25.7^{1.2}_{1.4}$ & $85.44771$ & $-1.92406$ & $0.3^{\prime}$ & $0.04^{\prime\prime}$ & $278.2$ \\
        \oddrow 5 & XRTC 001204 & 1882 & $96.8$ & \makecell{2000-12-02/\\2000-12-04} & $57.3^{23.2}_{13.3}$ & $91.90500$ & $-6.38148$ & $3.4^{\prime}$ & $0.21^{\prime\prime}$ & $25.8$ \\
        \evenrow 6 & XRTC 001204 & 1882 & $96.8$ & \makecell{2000-12-02/\\2000-12-04} & $54.4^{39.4}_{19.1}$ & $91.89683$ & $-6.38541$ & $3.9^{\prime}$ & $0.32^{\prime\prime}$ & $8.0$ \\
        \oddrow 7 & XRTC 001204 & 1882 & $96.8$ & \makecell{2000-12-02/\\2000-12-04} & $76.2^{2.4}_{12.3}$ & $91.94014$ & $-6.38184$ & $1.3^{\prime}$ & $0.24^{\prime\prime}$ & $10.9$ \\
        \evenrow 8 & XRTC 001204 & 1882 & $96.8$ & \makecell{2000-12-02/\\2000-12-04} & $54.0^{10.3}_{16.5}$ & $91.94413$ & $-6.37715$ & $1.1^{\prime}$ & $0.11^{\prime\prime}$ & $28.0$ \\
        \oddrow 9 & XRTC 021001 & 2736 & $65.2$ & \makecell{2002-09-30/\\2002-10-01} & $18.3^{10.3}_{17.7}$ & $6.04418$ & $-72.09146$ & $0.6^{\prime}$ & $0.16^{\prime\prime}$ & $8.9$ \\
        \evenrow 10 & XRTC 020713 & 3184 & $87.5$ & \makecell{2002-07-12/\\2002-07-13} & $60.0^{6.1}_{9.8}$ & $104.40282$ & $-55.81076$ & $8.7^{\prime}$ & $1.22^{\prime\prime}$ & $10.9$ \\
        \oddrow 11 & XRTC 020518 & 3214 & $14.9$ & 2002-05-18 & $9.0^{3.7}_{1.3}$ & $238.11094$ & $20.19988$ & $4.9^{\prime}$ & $0.70^{\prime\prime}$ & $14.6$ \\
        \evenrow 12 & XRTC 030122 & 3498 & $69.0$ & \makecell{2003-01-21/\\2003-01-22} & $41.0^{15.3}_{21.0}$ & $83.82902$ & $-5.47276$ & $4.7^{\prime}$ & $0.77^{\prime\prime}$ & $7.3$ \\
        \oddrow 13 & XRTC 030112 & 3744 & $164.2$ & \makecell{2003-01-10/\\2003-01-12} & $142.4^{7.7}_{9.9}$ & $83.62232$ & $-5.39870$ & $11.8^{\prime}$ & $0.00^{\prime\prime}$ & $68.3$ \\
        \evenrow 14 & XRT 030511 & 4062 & $46.1$ & \makecell{2003-05-10/\\2003-05-11} & $14.5^{9.8}_{6.0}$ & $76.77818$ & $-31.86982$ & $10.7^{\prime}$ & $0.74^{\prime\prime}$ & $41.9$ \\
        \oddrow 15 & XRTC 030117 & 4374 & $169.0$ & \makecell{2003-01-15/\\2003-01-17} & $113.6^{84.9}_{29.9}$ & $83.77555$ & $-5.38505$ & $2.7^{\prime}$ & $0.25^{\prime\prime}$ & $9.9$ \\
        \evenrow 16 & XRTC 030120 & 4396 & $164.6$ & \makecell{2003-01-18/\\2003-01-20} & $53.3^{41.5}_{7.9}$ & $83.88027$ & $-5.37104$ & $3.9^{\prime}$ & $0.38^{\prime\prime}$ & $13.8$ \\
        \oddrow 17 & XRTC 040802 & 5353 & $36.6$ & \makecell{2004-08-01/\\2004-08-02} & $29.2^{1.4}_{10.6}$ & $329.12392$ & $-4.83024$ & $4.0^{\prime}$ & $0.51^{\prime\prime}$ & $6.9$ \\
        \evenrow 18 & XRTC 040802 & 5353 & $36.6$ & \makecell{2004-08-01/\\2004-08-02} & $34.0^{0.1}_{1.4}$ & $329.14680$ & $-4.86583$ & $5.4^{\prime}$ & $0.84^{\prime\prime}$ & $3.9$ \\
        \oddrow 19 & XRT 041230 & 5885 & $70.7$ & \makecell{2004-12-30/\\2004-12-31} & $30.9^{3.0}_{17.8}$ & $318.12660$ & $-63.49898$ & $3.7^{\prime}$ & $0.42^{\prime\prime}$ & $8.8$ \\
        \evenrow 20 & XRTC 060706 & 6436 & $36.5$ & \makecell{2006-07-05/\\2006-07-06} & $23.0^{5.7}_{9.7}$ & $52.24340$ & $31.37147$ & $1.6^{\prime}$ & $0.12^{\prime\prime}$ & $38.6$ \\
        \oddrow 21 & XRTC 060706 & 6436 & $36.5$ & \makecell{2006-07-05/\\2006-07-06} & $25.3^{0.9}_{2.2}$ & $52.28227$ & $31.36582$ & $1.3^{\prime}$ & $0.22^{\prime\prime}$ & $20.6$ \\
        \evenrow 22 & XRTC 070612 & 7439 & $34.1$ & \makecell{2007-06-11/\\2007-06-12} & $16.3^{6.3}_{9.8}$ & $296.11682$ & $50.58232$ & $4.6^{\prime}$ & $0.53^{\prime\prime}$ & $12.9$ \\
        \oddrow 23 & XRT 080819 & 9841 & $15.8$ & 2008-08-19 & $8.4^{1.6}_{3.9}$ & $175.00503$ & $-31.91742$ & $4.7^{\prime}$ & $0.73^{\prime\prime}$ & $10.5$ \\
        \evenrow 24 & XRTC 090301 & 9923 & $14.7$ & 2009-03-01 & $7.8^{1.0}_{3.6}$ & $193.92558$ & $38.35555$ & $4.5^{\prime}$ & $0.68^{\prime\prime}$ & $5.8$ \\
        \oddrow 25 & XRTC 081224 & 10234 & $31.7$ & 2008-12-24 & $25.8^{2.5}_{2.5}$ & $59.83881$ & $10.47411$ & $7.1^{\prime}$ & $0.93^{\prime\prime}$ & $10.4$ \\
        \evenrow 26 & XRTC 100914 & 11737 & $52.3$ & 2010-09-14 & $31.1^{0.4}_{26.1}$ & $337.78288$ & $39.37290$ & $1.6^{\prime}$ & $0.24^{\prime\prime}$ & $8.0$ \\
        \oddrow 27 & XRTC 100101 & 11777 & $29.2$ & 2010-01-01 & $24.0^{1.0}_{2.3}$ & $138.08401$ & $35.05535$ & $1.9^{\prime}$ & $0.13^{\prime\prime}$ & $44.4$ \\
        \evenrow 28 & XRT 100831 & 12264 & $40.0$ & 2010-08-31 & $8.6^{0.9}_{4.8}$ & $90.00443$ & $-52.71504$ & $4.7^{\prime}$ & $0.55^{\prime\prime}$ & $12.1$ \\
        \oddrow 29 & XRTC 111009 & 12273 & $9.9$ & \makecell{2011-10-08/\\2011-10-09} & $7.2^{1.6}_{1.5}$ & $87.16240$ & $-25.56932$ & $5.6^{\prime}$ & $0.75^{\prime\prime}$ & $9.9$ \\
        \evenrow 30 & XRTC 111003 & 12315 & $39.2$ & \makecell{2011-10-02/\\2011-10-03} & $28.3^{2.0}_{3.1}$ & $36.43187$ & $12.87232$ & $1.4^{\prime}$ & $0.11^{\prime\prime}$ & $49.1$ \\
        \oddrow 31 & XRT 110103 & 12884 & $84.5$ & \makecell{2011-01-03/\\2011-01-04} & $60.9^{10.3}_{8.9}$ & $212.12047$ & $-27.05800$ & $13.0^{\prime}$ & $0.81^{\prime\prime}$ & $33.7$ \\
        \evenrow 32 & XRT 110919 & 13454 & $91.8$ & \makecell{2011-09-19/\\2011-09-20} & $64.1^{12.0}_{29.3}$ & $15.93569$ & $-21.81271$ & $7.4^{\prime}$ & $0.65^{\prime\prime}$ & $16.7$ \\
        \oddrow 33 & XRT 130822 & 14904 & $29.7$ & 2013-08-22 & $14.4^{3.4}_{4.0}$ & $345.49250$ & $15.94870$ & $1.6^{\prime}$ & $0.17^{\prime\prime}$ & $13.4$ \\
        \evenrow 34 & XRT 140327 & 15113 & $33.6$ & 2014-03-27 & $15.4^{0.7}_{5.6}$ & $45.26836$ & $-77.88092$ & $6.6^{\prime}$ & $1.30^{\prime\prime}$ & $7.6$ \\
        \oddrow 35 & XRT 141001/CDF-S XT1 & 16454 & $47.1$ & 2014-10-01 & $5.0^{10.0}_{3.0}$ & $53.16163$ & $-27.85949$ & $3.7^{\prime}$ & $0.17^{\prime\prime}$ & $47.1$ \\
        \multicolumn{11}{p{0.5\linewidth}}{\textbf{Notes:} }
    \end{tabular}
    \label{tab:enter_label}
\end{table}

In [3]:
# plot multifig of light curve and long light curve

# parameters
date_range = [
    # '',
    '2015-01-01',
    '2022-04-01',
    # ''
]

window_size = 20
exclusions = []

# get the de
detections = get_candidates(window_size, date_range[0], date_range[1], exclusions)

# divide the detections into multiple dataframes
group_size = 6
detections = [detections.iloc[i:i + group_size] for i in range(0, len(detections), group_size)]

for number, detection_group in enumerate(detections):
    plot_light_curve_multifig(detection_group, f'multifig_20ks_paperII_{number}')

/home/jcrans/miniconda3/envs/ciao-4.16/lib/python3.11/site-packages/matplotlib/cbook.py:1699: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  return math.isfinite(val)

No files found for 494
494 - Error: cannot unpack non-iterable int object
No files found for 634
634 - Error: cannot unpack non-iterable int object
No files found for 581
581 - Error: cannot unpack non-iterable int object
No files found for 1431
1431 - Error: cannot unpack non-iterable int object

In [8]:
# plot the light curves of the candidates with no matches

# parameters
date_range = [
    # '',
    # '2015-01-01',
    '2022-04-01',
    ''
]

window_size = 20
exclusions = []

# no_matches = get_no_match_fxts(window=20, from_date=date_range[0], to_date=date_range[1])
no_matches = get_new_detections(20, True)
no_matches = get_candidates(window_size, date_range[0], date_range[1], exclusions)

for i, fxt in no_matches.iterrows():
    # pass
    lc = gen_light_curve(
        fxt['ObsId'],
        float(fxt['RA']),
        float(fxt['DEC']),
        float(fxt['THETA']),
    )
    print(fxt['ObsId'])
    plot_light_curve(
        fxt['ObsId'],
        float(fxt['RA']),
        float(fxt['DEC']),
        float(fxt['THETA']),
    )

27611
23580
25212
22475
29320
23377
26643
25452
12317
15720
15720
18901
23485
1047
1520
1520
805
16024
6859
10303
10326
11674
13956
17036
19515
1711
1712
1712
894
926
4970
5757
8500
13020
18297
2253
4396
20617
11029
11029
13733
16745
21676
4449
18454
344
6830
7801
10351
16046
3265
5353
5353
7191
5800
11744
13471
16449
17308

In [2]:
# get table of number of observations, analysed observations, detections and no match detections

date_range = [
    # '',
    '2015-01-01',
    '2022-04-01',
    # ''
]

candidate_numbers = get_candidate_numbers(
    from_date=date_range[0], to_date=date_range[1], window=20.0)

column_names = {
    'Before': 'Paper I',
    'In': 'Paper II',
    'After': 'New Data'
}
candidate_numbers = candidate_numbers.rename(columns=column_names)

# print(dataframe_to_latex(candidate_numbers))
candidate_numbers

18 71 35

             Total Paper I Paper II New Data
Observations  9799    4992     3311     1496
Analysed      9302    4577     3229     1496
Detections     456      71       18       35
Candidates      27       5        0        1

In [4]:
# get the criteria table for a certain date range like in the papers

date_range = [
    '',
    # '2015-01-01',
    # '2022-04-01',
    ''
]

criteria_table = get_criteria_table(from_date=date_range[0], to_date=date_range[1], window=50)

print(dataframe_to_latex(criteria_table))
# criteria_table

\begin{table}[h]
    \centering
    \caption{}
    \begin{tabular}{ccccc}
        \headerrow & \headercell{Matched} & \headercell{Unique Matched} & \headercell{Removed} & \headercell{Remaining} \\
        \oddrow Archival X-ray date & 474 & 46 & 474 & 141 \\
        \evenrow Cross-match with stars/Gaia & 389 & 36 & 78 & 63 \\
        \oddrow NED + SIMBAD + VizieR & 438 & 19 & 20 & 40 \\
        \multicolumn{5}{p{0.5\linewidth}}{\textbf{Notes:} }
    \end{tabular}
    \label{tab:enter_label}
\end{table}

In [3]:
# check if fxts from papers are found in new code
paper_I_fxts = [
    [803, 186.38125, 13.06607],
    [2025, 167.86792, 55.67253],
    [8490, 201.24329, -43.04060],
    [9546, 211.25113, 53.65706],
    [9548, 170.07296, 12.97189],
    [14904, 345.49250, 15.94871],
    [4062, 76.77817, -31.86980],
    [5885, 318.12646, -63.49914],
    [9841, 175.00504, -31.91743],
    [12264, 90.00450, -52.71501],
    [12884, 212.12063, -27.05784],
    [13454, 15.93558, -21.81272],
    [15113, 45.26725, -77.88095],
    [16454, 53.16158, -27.85940],
]

paper_II_fxts = [
    [16093, 233.73496, 23.46849],
    [16453, 53.07672, -27.87345],
    [18715, 40.82972, 32.32390],
    [19310, 36.71489, -1.08317],
    [20635, 356.26437, -42.64494],
    [21831, 207.34711, 26.58421 ],
    [23103, 50.47516, 41.24704],
    [24604, 207.23523, 26.66230],
]

# paper_I_fxts = pd.DataFrame(paper_I_fxts, columns=['ObsId', 'RA', 'DEC'])
# paper_II_fxts = pd.DataFrame(paper_II_fxts, columns=['ObsId', 'RA', 'DEC'])

analysed = pd.read_csv('output/analysed_w20.txt', header=0, sep=' ', dtype=str)

print('Paper I FXTs')
for fxt in paper_I_fxts:
    detections = get_detections(str(fxt[0]), fxt[1], fxt[2], True)
    if not detections.empty:
        print(detections[['ObsId', 'RA', 'DEC']].to_string(index=False, header=False))
    elif not analysed[analysed['ObsId'] == str(fxt[0])].empty:
        print(f'{fxt[0]} - not detected')
    else:
        print(f'{fxt[0]} - not analysed')
print('')
print('Paper II FXTs')
for fxt in paper_II_fxts:
    detections = get_detections(str(fxt[0]), fxt[1], fxt[2], True)
    if not detections.empty:
        print(detections[['ObsId', 'RA', 'DEC']].to_string(index=False, header=False))
    elif not analysed[analysed['ObsId'] == str(fxt[0])].empty:
        print(f'{fxt[0]} - not detected')
    else:
        print(f'{fxt[0]} - not analysed')

Paper I FXTs
803 186.381579 13.066452
2025 167.86794 55.672528
8490 201.24335 -43.040584
9546 211.251125 53.65706
9548 170.072881 12.971883
14904 345.492502 15.948704
4062 76.778177 -31.86982
5885 318.126599 -63.49898
9841 175.005028 -31.917419
12264 90.004429 -52.715044
12884 212.120467 -27.057995
13454 15.935694 -21.812707
15113 45.268361 -77.880922
16454 53.161632 -27.859487

Paper II FXTs
16093 233.734807 23.468395
16453 53.076762 -27.873612
18715 40.829608 32.323772
19310 - not analysed
20635 356.264589 -42.644933
21831 207.347187 26.584447
23103 50.47529 41.246834
24604 - not detected

In [4]:
# get fxt table for certain date range

date_range = [
    # '',
    # '2015-01-01',
    '2022-04-01',
    ''
]

no_match = get_fxt_table(from_date=date_range[0], to_date=date_range[1])
no_match = no_match[no_match['ObsId'] != 2561]
# reset indices to integers starting from 1
no_match = no_match.reset_index(drop=True) # this starts from 0
no_match.index += 1
no_match = no_match.drop(columns=['Prev. Det.'])

no_match

,Id,ObsId,Exp. (ks),Date,$T_{90}$,RA (deg),Dec (deg),Off. Ang.,Pos. Unc.,S/N
1,XRTC 210515,23488,$29.6$,2021-05-15,$25.0^{3.3}_{10.3}$,$187.66173$,$41.63609$,$2.5\arcmin$,$0.18\arcsec$,$28.1$
2,XRTC 231009,28964,$12.4$,2023-10-09,$2.0^{0.2}_{0.7}$,$244.71650$,$-1.99187$,$6.1\arcmin$,$0.72\arcsec$,$5.7$

In [3]:
# get fxt dataframe for detections

date_range = [
    # '',
    # '2015-01-01',
    '2022-04-01',
    ''
]

detections = get_new_detections(50, True)
dataframe = get_fxt_dataframe_detections(detections)

dataframe.to_csv('tables/all_50ks.csv', index=True)
dataframe

\begin{table}[h]
    \centering
    \caption{}
    \begin{tabular}{cccccccccccc}
        \headerrow & \headercell{Id} & \headercell{Previous Detection} & \headercell{ObsId} & \headercell{Exp. (ks)} & \headercell{Date} & \headercell{T_90} & \headercell{RA (deg)} & \headercell{Dec (deg)} & \headercell{Off. Ang.} & \headercell{Pos. Unc.} & \headercell{S/N} \\
        \multicolumn{12}{p{0.5\linewidth}}{\textbf{Notes:} }
    \end{tabular}
    \label{tab:enter_label}
\end{table}

In [7]:
# get fxt table for new detections in 10 ks comapred to 20ks

new_detections = get_new_detections(10, True)
fxt_table = get_fxt_dataframe_detections(new_detections)
fxt_table = fxt_table.drop(columns=['Previous Detection'])

# print(dataframe_to_latex(fxt_table))
fxt_table

,Id,ObsId,Exp. (ks),Date,T_90,RA (deg),Dec (deg),Off. Ang.,Pos. Unc.,S/N
1,XRTC 000222,344,47.4,2000-02-21 - 2000-02-22,43.4 +0.6 -0.5,40.66962,-0.01274,0.6,0.02,523.8
2,XRTC 000209,805,40.8,2000-02-08 - 2000-02-09,13.3 +1.1 -1.2,142.94319,55.19166,18.9,1.12,18.0
3,XRTC 001021,894,39.4,2000-10-20 - 2000-10-21,35.8 +1.4 -1.3,258.02855,64.14214,6.0,0.24,66.5
4,XRTC 000611,926,44.2,2000-06-11,39.3 +3.6 -3.0,152.67783,-12.87157,13.2,1.34,20.3
5,XRTC 001009,1047,32.2,2000-10-09,29.2 +2.0 -1.4,255.86135,51.95720,12.7,1.17,31.5
6,XRTC 000203,1520,23.7,2000-02-03,21.0 +1.6 -1.7,154.84019,41.34584,15.4,2.11,18.7
7,XRTC 000203,1520,23.7,2000-02-03,21.1 +1.6 -1.5,154.71636,41.25359,14.5,1.91,17.6
8,XRTC 000614,1711,27.1,2000-06-14,25.3 +0.9 -1.0,187.12791,1.69688,24.4,3.42,6.9
9,XRTC 000614,1712,27.4,2000-06-14,25.0 +1.0 -1.0,187.27452,2.04868,0.4,0.00,72.8
10,XRTC 000614,1712,27.4,2000-06-14,24.2 +1.0 -1.1,187.27417,2.04826,0.4,0.06,70.2
11,XRTC 020115,2253,47.4,2002-01-14 - 2002-01-15,41.9 +2.2 -3.5,187.20522,75.58803,9.7,0.68,41.2
12,XRTC 021002,3265,17.9,2002-10-02,16.2 +1.3 -0.8,29.95563,-8.83288,2.2,0.14,78.0
13,XRTC 030120,4396,164.6,2003-01-18 - 2003-01-20,45.2 +20.4 -44.4,83.84385,-5.33084,4.1,0.15,44.9
14,XRTC 030812,4449,18.2,2003-08-11 - 2003-08-12,15.8 +2.3 -1.0,22.53429,21.81805,4.7,0.40,35.7
15,XRTC 041023,4970,98.8,2004-10-22 - 2004-10-23,87.5 +2.0 -2.7,139.50595,-11.76927,18.5,1.44,8.0
16,XRTC 040802,5353,36.6,2004-08-01 - 2004-08-02,32.7 +2.0 -1.8,329.35219,-4.68083,12.6,1.54,17.7
17,XRTC 040802,5353,36.6,2004-08-01 - 2004-08-02,34.7 +3.0 -1.2,329.41304,-4.69677,15.6,2.61,7.3
18,XRTC 050903,5757,59.0,2005-09-02 - 2005-09-03,53.9 +3.5 -3.9,180.82716,57.80398,6.3,0.29,80.9
19,XRTC 051023,5800,44.5,2005-10-22 - 2005-10-23,41.1 +1.8 -1.5,64.86444,2.55921,4.0,0.13,151.9
20,XRTC 060903,6830,94.4,2006-09-02 - 2006-09-03,86.8 +3.8 -3.4,14.73732,26.95390,9.0,0.40,55.2
21,XRTC 060514,6859,14.8,2006-05-14,12.2 +1.9 -1.1,242.97912,52.46081,2.0,0.14,38.1
22,XRTC 060519,7191,69.2,2006-05-19,63.9 +3.1 -4.1,61.16424,-41.03927,5.7,0.20,83.5
23,XRTC 070910,7801,14.6,2007-09-10,12.9 +1.0 -1.1,24.92968,-10.50559,12.6,1.90,13.6
24,XRTC 061230,8500,21.8,2006-12-30,15.0 +0.8 -1.2,130.24038,32.61128,11.2,2.24,7.8
25,XRTC 090108,10303,59.5,2009-01-08,55.0 +2.0 -3.0,103.95847,54.41777,16.8,1.43,15.7
26,XRTC 090323,10326,10.0,2009-03-23,8.8 +0.9 -0.5,141.68290,2.55548,3.3,0.25,41.3
27,XRTC 090815,10351,14.8,2009-08-15,12.9 +2.3 -0.8,351.69291,9.89682,15.2,4.02,6.5
28,XRTC 090826,11029,34.2,2009-08-26,31.7 +0.9 -0.7,322.49172,12.16696,0.0,0.04,274.5
29,XRTC 090826,11029,34.2,2009-08-26,31.2 +0.8 -0.7,322.49227,12.16803,0.1,0.05,283.0
30,XRTC 100320,11674,14.8,2010-03-20,13.3 +1.1 -1.1,199.36469,-16.79776,11.9,1.13,40.0
31,XRTC 090903,11744,69.1,2009-09-03,63.7 +2.8 -2.5,355.81474,-55.38966,2.4,0.06,197.9
32,XRTC 110501,12317,78.5,2011-04-30 - 2011-05-01,72.7 +4.0 -3.1,191.87038,-2.23492,4.5,0.12,97.6
33,XRTC 100810,13020,41.5,2010-08-10,37.2 +3.0 -2.3,239.06231,66.34653,3.2,0.19,64.1
34,XRTC 120812,13471,55.2,2012-08-11 - 2012-08-12,50.6 +2.6 -2.6,3.67566,-49.88649,3.9,0.09,141.1
35,XRTC 121114,13733,18.8,2012-11-14,15.7 +0.6 -0.5,283.77740,-22.70123,0.3,0.04,284.7
36,XRTC 120210,13956,20.1,2012-02-10,17.7 +1.6 -1.6,133.35603,50.54639,10.3,2.41,7.7
37,XRTC 131208,15720,27.6,2013-12-08,25.8 +1.2 -0.7,189.30803,-41.03530,13.1,1.35,35.7
38,XRTC 131208,15720,27.6,2013-12-08,24.7 +2.4 -1.5,189.30326,-40.85130,2.2,0.14,38.4
39,XRTC 140607,16024,29.6,2014-06-07,26.6 +2.3 -1.7,204.24157,-29.85993,0.5,0.08,75.6
40,XRTC 140925,16046,11.9,2014-09-25,9.8 +1.9 -0.5,17.60692,31.74725,2.8,0.13,46.6
41,XRTC 150928,16449,24.6,2015-09-28,22.2 +0.3 -0.3,84.44676,-69.17207,6.8,0.08,377.8
42,XRTC 160610,16745,45.4,2016-06-09 - 2016-06-10,41.5 +3.9 -2.3,64.37744,-62.78640,0.2,0.09,36.9
43,XRTC 151207,17036,12.9,2015-12-07,10.7 +2.0 -2.8,132.85745,39.59486,0.3,0.14,34.9
44,XRTC 150711,17308,44.8,2015-07-10 - 2015-07-11,40.2 +1.7 -1.9,34.02208,-5.27619,20.0,2.10,9.3
45,XRTC 160328,18297,11.9,2016-03-28,10.0 +0.9 -0.4,186.58560,-49.20328,6.7,0.46,44.6
46,XRTC 160629,18454,49.5,2016-06-29,45.1 +0.7 -0.9,287.51061,-63.83472,2.0,0.03,975.9
47,XRTC 170404,18901,59.4,2017-04-04,53.7 +1.5 -2.8,182.01652,-38.96964,3.8,0.08,255.7
48,XRTC 180114,19515,32.6,2018-01-13 - 2018-01-14,29.7 +2.5 -1.5,150.50757,45.31461,10.0,1.20,21.9
49,XRTC 190213,20617,23.8,2019-02-12 - 2019-02-13,21.9 +5.2 -1.9,4.62894,44.02895,0.8,0.14,37.9
50,XRTC 180825,21676,65.5,2018-08-24 - 2018-08-25,59.4 +3.3 -3.6,349.04590,-42.58517,0.1,0.09,99.0
51,XRTC 210705,22475,22.4,2021-07-05,13.6 +5.8 -3.1,110.91872,80.27623,11.2,2.59,6.6
52,XRTC 210605,23377,28.6,2021-06-05,26.6 +1.0 -0.8,45.46007,-16.59322,0.4,0.05,440.3
53,XRTC 210221,23485,32.2,2021-02-21,29.1 +1.7 -1.1,187.62640,41.64835,2.9,0.13,59.4
54,XRTC 211129,23580,29.7,2021-11-29,26.1 +1.8 -1.8,170.24664,39.17189,3.8,0.18,80.2
55,XRTC 230101,25212,13.1,2023-01-01,11.8 +1.2 -0.6,228.92389,-19.36898,6.0,0.51,41.5
56,XRTC 221220,25452,12.8,2022-12-20,7.1 +1.6 -4.4,333.81844,37.12188,11.5,2.60,9.8
57,XRTC 221104,26643,18.8,2022-11-04,17.4 +1.4 -0.7,50.04502,8.74877,0.2,0.13,56.6
58,XRTC 221225,27611,19.8,2022-12-24 - 2022-12-25,17.4 +1.6 -1.7,184.73933,11.12729,0.6,0.07,212.8
59,XRTC 240316,29320,10.9,2024-03-16,5.3 +2.4 -1.0,169.58073,0.50314,6.3,1.06,5.9

In [8]:
# get fxt table for new detections in 30 ks compared to 20 ks

new_detections = get_new_detections(30, True)
fxt_table = get_fxt_dataframe_detections(new_detections)
fxt_table = fxt_table.drop(columns=['Previous Detection'])

# print(dataframe_to_latex(fxt_table))
fxt_table

,Id,ObsId,Exp. (ks),Date,T_90,RA (deg),Dec (deg),Off. Ang.,Pos. Unc.,S/N
1,XRTC 000322,829,47.0,2000-03-21 - 2000-03-22,38.0 +15.5 -7.4,69.30900,29.71758,4.1,0.35,10.7
2,XRTC 001204,1882,96.8,2000-12-02 - 2000-12-04,77.1 +14.5 -2.5,91.94128,-6.40028,1.6,0.16,27.5
3,XRTC 020521,2949,34.2,2002-05-21,27.3 +8.1 -9.9,200.55265,-36.74750,7.2,1.73,7.0
4,XRTC 030706,3951,89.1,2003-07-05 - 2003-07-06,74.1 +17.8 -5.5,170.32906,53.06506,4.8,0.67,13.9
5,XRTC 030120,4396,164.6,2003-01-18 - 2003-01-20,45.2 +20.4 -44.4,83.84385,-5.33084,4.1,0.15,44.9
6,XRTC 040913,5023,67.2,2004-09-12 - 2004-09-13,52.6 +2.4 -7.4,161.51616,59.11211,6.0,0.81,11.1
7,XRTC 091103,10453,34.7,2009-11-03,29.5 +5.7 -4.4,216.61302,33.75577,6.0,0.72,10.3
8,XRTC 100819,12301,78.0,2010-08-18 - 2010-08-19,58.7 +8.6 -3.0,148.88870,68.96563,3.2,0.42,7.1
9,XRTC 110501,12317,78.5,2011-04-30 - 2011-05-01,76.6 +4.9 -3.5,191.86629,-2.15688,0.6,0.12,33.2
10,XRTC 110811,13478,79.4,2011-08-10 - 2011-08-11,73.1 +3.3 -2.5,311.08752,-50.59842,7.0,0.48,44.1

In [9]:
# get fxt table for new detections in 50 compared to 20 ks

new_detections = get_new_detections(50, True)
fxt_table = get_fxt_dataframe_detections(new_detections)
fxt_table = fxt_table.drop(columns=['Previous Detection'])

# print(dataframe_to_latex(fxt_table))

fxt_table

,Id,ObsId,Exp. (ks),Date,T_90,RA (deg),Dec (deg),Off. Ang.,Pos. Unc.,S/N
1,XRTC 001204,1882,96.8,2000-12-02 - 2000-12-04,70.0 +11.1 -7.4,91.94792,-6.39343,1.0,0.18,15.1
2,XRTC 030120,4396,164.6,2003-01-18 - 2003-01-20,45.2 +20.4 -44.4,83.84385,-5.33084,4.1,0.15,44.9
3,XRTC 060530,6792,97.3,2006-05-29 - 2006-05-30,90.5 +17.9 -4.1,221.89159,9.33420,6.0,0.85,9.7
4,XRTC 100819,12301,78.0,2010-08-18 - 2010-08-19,58.7 +8.6 -3.0,148.88870,68.96563,3.2,0.42,7.1
5,XRTC 110501,12317,78.5,2011-04-30 - 2011-05-01,76.6 +4.9 -3.5,191.86629,-2.15688,0.6,0.12,33.2